# Generated by Django 2.2.8 on 2020-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantitiy',
            field=models.IntegerField(default=1),
        ),
    ]
