# Generated by Django 2.2.8 on 2020-07-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_quantitiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
